PUT http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NmEwZGFmN2JlNzllYzQ4Y2IyNGIzODIiLCJpYXQiOjE3MjIyNTAxMjJ9.AnEmV3Om-NmPK0ym3glsfgMicqLzCXOTwKBnNua4Ijo

{
    "userId": "66a0daf7be79ec48cb24b382",
    "author": "Brooke Rupert",
    "title": "Letters from America",
    "url": "https://openlibrary.org/works/OL1826190W/Letters_from_America",
    "likes": 5,
    "id": "66a0dca4a354f56256ac8db3"
}
